(function(){
'use strict';
const V=2,F=1001,G=1002,A=1003;
const c1=`Habits rarely appear from nowhere. They usually begin with a cue: a time, place, feeling, or event that tells the brain what to do next. When the same response follows the same cue repeatedly, the behavior can become automatic. This saves mental effort because the brain no longer needs to make a fresh decision every time.\n\nA notification, for example, may cue someone to open a social-media app before they have consciously decided to do so. The reward that follows—new information, amusement, or social approval—helps reinforce the loop. Over time, the cue, routine, and reward become linked.`;
const c2=`Repetition matters because the brain learns from patterns. A behavior performed once may be easy to forget, but a behavior repeated in a stable context becomes easier to retrieve. Importantly, consistency is often more useful than intensity.\n\nReading ten pages every evening may build a stronger reading habit than reading one hundred pages on a single Sunday and then stopping for a week. Small actions also reduce friction: when a task feels easy to start, people are more likely to begin it.`;
const c3=`Changing a habit therefore requires more than willpower. One useful strategy is to redesign the environment so that good cues are visible and bad cues are harder to reach. A student who wants to read more might leave a book on the desk and keep the phone in another room.\n\nAnother strategy is to make the desired behavior specific: instead of saying “I will study more,” decide when, where, and for how long you will study. Missing one day does not erase a habit; the important step is to resume before a temporary break becomes a new pattern.`;
const guide=`Welcome to the Smart Reader sample. This short guide is a hands-on tour of the features that are already available.\n\nOpen Vocabulary to see words with their surface form, meaning, part of speech, tags, memo, and original context. Open Notes to inspect translations, explanations, and sentence structure. Open Problems to try review questions with types, tags, difficulty, and answer history.\n\nFrom the library or vocabulary screen, start Flashcards to practice with swipe judgments, answer counts, copying, and audio playback. You can also switch chapters, search inside a text, add bookmarks, and export or back up your data.`;
const W=(id,ch,word,surface,meaning,pos,tags,memo,context)=>({id,chapterId:ch,word,surfaceText:surface,meaning,partOfSpeech:pos,tags,memo,context,memorized:false});
const Q=(id,ch,selectedText,question,answer,explanation,type,tags,difficulty,needsReview=false)=>({id,chapterId:ch,selectedText,question,answer,explanation,memo:'',questionType:type,tags,difficulty,needsReview,attempts:[]});
const N=(id,ch,originalText,translation,extra,annotations,relations)=>({id,chapterId:ch,originalText,translation,extra,structure:{annotations,relations}});
const DATA=[
{id:F,type:'folder',name:'📚 Smart Reader サンプル',parentId:null,sampleVersion:V},
{id:G,type:'article',name:'① Smart Readerを試す',parentId:F,sampleVersion:V,sourceType:'sample',sourceName:'Smart Reader Sample',url:'',content:guide,chapters:[{id:'sample-guide',title:'Start Here',content:guide,order:0}],words:[
W(2101,'sample-guide','hands-on','hands-on','実践的な、実際に操作して学ぶ','adjective',['重要','学習'],'hands-on experience / hands-on practice の形でよく使う。','This short guide is a hands-on tour of the features that are already available.'),
W(2102,'sample-guide','inspect','inspect','～を詳しく調べる、確認する','verb',['重要'],'see より「注意して詳しく見る」という含み。','Open Notes to inspect translations, explanations, and sentence structure.'),
W(2103,'sample-guide','playback','playback','再生','noun',['機能'],'audio playback で「音声再生」。','From the library or vocabulary screen, start Flashcards to practice with swipe judgments, answer counts, copying, and audio playback.')],notes:[
N(3101,'sample-guide','This short guide is a hands-on tour of the features that are already available.','この短いガイドでは、すでに利用できる機能を実際に触りながら確認できます。','that are already available は the features を修飾する関係詞節です。',[
{id:'g1',text:'This short guide',occurrence:1,kind:'core',label:'S'},{id:'g2',text:'is',occurrence:1,kind:'core',label:'V'},{id:'g3',text:'a hands-on tour of the features that are already available',occurrence:1,kind:'core',label:'C'},{id:'g4',text:'that are already available',occurrence:1,kind:'modifier',notation:'square'},{id:'g5',text:'are',occurrence:1,kind:'core',label:"V'"},{id:'g6',text:'already',occurrence:1,kind:'modifier',notation:'angle'},{id:'g7',text:'available',occurrence:1,kind:'core',label:"C'"}],
[{from:'g4',to:'g3',type:'modifies'},{from:'g6',to:'g7',type:'modifies'}])],questions:[Q(4101,'sample-guide','Open Notes to inspect translations, explanations, and sentence structure.','Notes では何を確認できると説明されていますか。','訳・解説・文構造です。','ガイド本文の Open Notes ... の一文に対応します。','reading',['使い方'],1)],bookmarks:[{id:5101,chapterId:'sample-guide',pIndex:2,label:'フラッシュカードの説明'}]},
{id:A,type:'article',name:'🧠 Why We Form Habits',parentId:F,sampleVersion:V,sourceType:'sample',sourceName:'Smart Reader Sample',url:'',content:[c1,c2,c3].join('\n\n'),chapters:[{id:'habit-1',title:'1. The Habit Loop',content:c1,order:0},{id:'habit-2',title:'2. Why Repetition Matters',content:c2,order:1},{id:'habit-3',title:'3. Designing Better Habits',content:c3,order:2}],words:[
W(2201,'habit-1','cue','cue','きっかけ、合図','noun',['重要','多義語'],'habit cue で「習慣を始動させるきっかけ」。','They usually begin with a cue: a time, place, feeling, or event that tells the brain what to do next.'),
W(2202,'habit-1','automatic','automatic','無意識的な、自動的な','adjective',['重要'],'become automatic で「無意識にできるようになる」。','When the same response follows the same cue repeatedly, the behavior can become automatic.'),
W(2203,'habit-1','reinforce','reinforce','～を強化する','verb',['重要','多義語'],'reinforce a habit / belief / structure など広く使える。','The reward that follows—new information, amusement, or social approval—helps reinforce the loop.'),
W(2204,'habit-2','repetition','Repetition','反復、繰り返し','noun',['重要'],'repeat の名詞形。','Repetition matters because the brain learns from patterns.'),
W(2205,'habit-2','retrieve','retrieve','～を取り出す、呼び出す','verb',['重要','多義語'],'記憶の文脈では「情報・記憶を呼び出す」。','A behavior performed once may be easy to forget, but a behavior repeated in a stable context becomes easier to retrieve.'),
W(2206,'habit-2','consistency','consistency','一貫性、継続性','noun',['重要'],'習慣の文脈では「継続して同じように行うこと」。','Importantly, consistency is often more useful than intensity.'),
W(2207,'habit-2','friction','friction','摩擦；（行動の）始めにくさ、抵抗','noun',['重要','比喩'],'ここでは行動開始時の心理的・実務的な抵抗。','Small actions also reduce friction: when a task feels easy to start, people are more likely to begin it.'),
W(2208,'habit-3','redesign','redesign','～を再設計する','verb',['重要'],'re- + design。','One useful strategy is to redesign the environment so that good cues are visible and bad cues are harder to reach.'),
W(2209,'habit-3','resume','resume','～を再開する','verb',['重要','多義語'],'resume doing / resume a task など。','Missing one day does not erase a habit; the important step is to resume before a temporary break becomes a new pattern.')],notes:[
N(3201,'habit-1','When the same response follows the same cue repeatedly, the behavior can become automatic.','同じ反応が同じきっかけの後に繰り返し続くと、その行動は無意識に行われるようになり得ます。','When節が主節全体を修飾します。become は第2文型を作り、automatic が補語です。',[
{id:'h11',text:'When the same response follows the same cue repeatedly',occurrence:1,kind:'modifier',notation:'square'},{id:'h12',text:'the same response',occurrence:1,kind:'core',label:"S'"},{id:'h13',text:'follows',occurrence:1,kind:'core',label:"V'"},{id:'h14',text:'the same cue',occurrence:1,kind:'core',label:"O'"},{id:'h15',text:'repeatedly',occurrence:1,kind:'modifier',notation:'angle'},{id:'h16',text:'the behavior',occurrence:1,kind:'core',label:'S'},{id:'h17',text:'can become',occurrence:1,kind:'core',label:'V'},{id:'h18',text:'automatic',occurrence:1,kind:'core',label:'C'}],[{from:'h11',to:'h17',type:'modifies'},{from:'h15',to:'h13',type:'modifies'}]),
N(3202,'habit-2','A behavior performed once may be easy to forget, but a behavior repeated in a stable context becomes easier to retrieve.','一度だけ行われた行動は忘れやすい一方、安定した状況で繰り返された行動は思い出しやすくなります。','performed once と repeated in a stable context は直前の behavior を修飾する過去分詞句です。',[
{id:'h21',text:'A behavior',occurrence:1,kind:'core',label:'S1'},{id:'h22',text:'performed once',occurrence:1,kind:'modifier',notation:'square'},{id:'h23',text:'may be',occurrence:1,kind:'core',label:'V1'},{id:'h24',text:'easy to forget',occurrence:1,kind:'core',label:'C1'},{id:'h25',text:'a behavior',occurrence:1,kind:'core',label:'S2'},{id:'h26',text:'repeated in a stable context',occurrence:1,kind:'modifier',notation:'square'},{id:'h27',text:'becomes',occurrence:1,kind:'core',label:'V2'},{id:'h28',text:'easier to retrieve',occurrence:1,kind:'core',label:'C2'}],[{from:'h22',to:'h21',type:'modifies'},{from:'h26',to:'h25',type:'modifies'}])],questions:[
Q(4201,'habit-1','the cue, routine, and reward become linked','本文で習慣のループを構成する3要素は何ですか。','cue（きっかけ）, routine（行動）, reward（報酬）です。','Chapter 1 の最後で3要素が linked になると説明されています。','reading',['内容理解'],1),
Q(4202,'habit-1','helps reinforce the loop','reinforce のこの文脈での意味を答えてください。','「強化する」です。','報酬が習慣ループをより強固にする、という意味です。','vocabulary',['語彙','重要'],2),
Q(4203,'habit-2','A behavior performed once may be easy to forget','performed once は文中で何を修飾していますか。','直前の A behavior を修飾しています。','過去分詞句による後置修飾です。','grammar',['文法','後置修飾'],3,true),
Q(4204,'habit-2','consistency is often more useful than intensity','空欄を本文通りに補ってください：consistency is often more useful ___ intensity.','than','比較級 more useful than ～ の形です。','blank',['比較'],1),
Q(4205,'habit-3','instead of saying “I will study more,” decide when, where, and for how long you will study','この部分を自然な日本語に訳してください。','「もっと勉強する」と言う代わりに、いつ、どこで、どのくらいの時間勉強するのかを決めなさい。','instead of ～ing は「～する代わりに」。','translation',['和訳','語法'],3)],bookmarks:[{id:5201,chapterId:'habit-1',pIndex:1,label:'報酬とreinforce'},{id:5202,chapterId:'habit-3',pIndex:0,label:'環境を変える戦略'}]}
];
const OLD_GUIDE='Smart Readerへようこそ！\n\nこのアプリは、英文を読みながら気になった単語やフレーズを素早く保存できるツールです。\n\n右下の「📋」ボタンでサイドパネルを開き、単語やノートを確認できます。また、「＋」ボタンで新しい単語を追加できます。\n\nサンプル単語の「Collaborator」がこの文章の中にあります。クリックしてみてください。';
const OLD_POM="The Pomodoro Technique is a time management method developed by Francesco Cirillo in the late 1980s.\n\nIt uses a timer to break work into intervals, traditionally 25 minutes in length, separated by short breaks. Each interval is known as a pomodoro, from the Italian word for 'tomato', after the tomato-shaped kitchen timer that Cirillo used as a university student.\n\nThe method is simple: choose a task, set the timer for 25 minutes, and work until the timer rings. Then, take a short break (about 5 minutes). After four pomodoros, take a longer break.";
const clone=()=>JSON.parse(JSON.stringify(DATA));
const empty=v=>v===undefined||(Array.isArray(v)&&v.length===0);
const keys=(o,a)=>o&&typeof o==='object'&&Object.keys(o).every(k=>a.includes(k));
function oldGuide(x){if(!x||x.id!==G||x.type!=='article'||x.parentId!==F||x.name!=='Smart Readerの使い方'||x.content!==OLD_GUIDE||x.url!=='https://example.com'||!keys(x,['id','type','name','parentId','content','url','words','notes','bookmarks','questions','chapters']))return false;if(!Array.isArray(x.words)||x.words.length!==1||!Array.isArray(x.notes)||x.notes.length!==1||!empty(x.bookmarks)||!empty(x.questions)||!empty(x.chapters))return false;const w=x.words[0],n=x.notes[0];return keys(w,['id','word','meaning','memo','memorized'])&&w.id===2001&&w.word==='Collaborator'&&w.meaning==='協力者、共同制作者'&&w.memo==='発音注意：kəlǽbəreitər'&&w.memorized===false&&keys(n,['id','originalText','translation','extra'])&&n.id===3001&&n.originalText==='Welcome to Smart Reader!'&&n.translation==='Smart Readerへようこそ！'&&n.extra==='基本の挨拶フレーズです。';}
function oldPom(x){if(!x||x.id!==A||x.type!=='article'||x.parentId!==F||x.name!=='🍅 The Pomodoro Technique'||x.content!==OLD_POM||x.url!=='https://en.wikipedia.org/wiki/Pomodoro_Technique'||!keys(x,['id','type','name','parentId','content','url','words','notes','bookmarks','questions','chapters']))return false;if(!Array.isArray(x.words)||x.words.length!==3||!Array.isArray(x.notes)||x.notes.length!==2||!empty(x.bookmarks)||!empty(x.questions)||!empty(x.chapters))return false;const e=[[2002,'interval','間隔、合間','発音: íntervəl'],[2003,'traditionally','伝統的に、慣例として','traditional (形容詞) の副詞形'],[2004,'separated','分けられた、離れた','separate (動詞/形容詞) の過去分詞形']];for(let i=0;i<3;i++){const w=x.words[i],z=e[i];if(!keys(w,['id','word','meaning','memo','memorized'])||w.id!==z[0]||w.word!==z[1]||w.meaning!==z[2]||w.memo!==z[3]||w.memorized!==false)return false;}const n=x.notes;return n.every(y=>keys(y,['id','originalText','translation','extra']))&&n[0].id===3002&&n[0].originalText==='It uses a timer to break work into intervals, traditionally 25 minutes in length, separated by short breaks.'&&n[0].translation==='この手法ではタイマーを使い、作業を短い休憩で区切られた（通常は25分間の）「間隔」へと分割します。'&&n[0].extra==='「separated by short breaks」は前の「intervals」を詳しく説明する過去分詞の後置修飾です。'&&n[1].id===3003&&n[1].originalText==="Each interval is known as a pomodoro, from the Italian word for 'tomato'"&&n[1].translation==='各インターバルは「ポモドーロ」として知られており、これはイタリア語で「トマト」を意味します。'&&n[1].extra==='「be known as ～」＝「～として知られている」という重要表現が含まれています。';}
function canUpgrade(a){if(!Array.isArray(a))return false;const f=a.find(x=>x?.id===F),g=a.find(x=>x?.id===G),p=a.find(x=>x?.id===A);if(!f||f.type!=='folder'||f.parentId!==null||f.name!=='📚 チュートリアル'||!keys(f,['id','type','name','parentId']))return false;const children=a.filter(x=>x&&x.parentId===F);return children.length===2&&oldGuide(g)&&oldPom(p);}
function replace(a){const ids=new Set([F,G,A]),i=a.findIndex(x=>ids.has(x?.id)),r=a.filter(x=>!ids.has(x?.id)),at=i<0?r.length:Math.min(i,r.length);return[...r.slice(0,at),...clone(),...r.slice(at)];}
function refresh(){try{typeof showLibrary==='function'&&showLibrary();}catch(_){}try{typeof renderList==='function'&&renderList(typeof currentTab==='string'?currentTab:'words');}catch(_){}try{window.SmartReaderStudy?.refresh?.();}catch(_){}try{window.SmartReaderNoteStructureUI?.refresh?.();}catch(_){}}
async function stored(){const t=Date.now();while(Date.now()-t<5000){try{const a=await db.getItem('library_items');if(Array.isArray(a)&&a.length)return a;}catch(_){}await new Promise(r=>setTimeout(r,60));}try{const a=await db.getItem('library_items');return Array.isArray(a)?a:[];}catch(_){return[];}}
async function migrate(){if(typeof db==='undefined')return;const a=await stored();let n=null;if(!a.length)n=clone();else if(canUpgrade(a))n=replace(a);if(!n)return;try{await db.setItem('library_items',n);if(typeof libraryItems!=='undefined')libraryItems=n;try{localStorage.setItem('smart-reader-sample-version',String(V));}catch(_){}refresh();}catch(e){console.error('Sample data v2 migration failed',e);}}
window.SmartReaderSampleDataV2={version:V,data:clone(),canUpgradeLegacySample:canUpgrade,migrate};
const start=()=>window.setTimeout(migrate,0);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
